# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d427446c6ed59d9e1c891990e519870e0daa624ebc43c97836e90c7b8bd41f57264d1138cccd17a3049d1b3202832714ba9913040306a7a731bc6fe861f72988

test:
  secret_key_base: eac4e179626d03b189e07aa908f03076ffc1574f61123f937eb260cd4ec9b57c07d127a68444c98b1c6f41ae5b9cb8cc13239c87b8df5992dc4e309aaf7d90b3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
